services:
    db:
        image: postgres:alpine
        environment:
            POSTGRES_DB: productosdb
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: Admin
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - mynetwork
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U admin -d productosdb" ]
            interval: 5s
            timeout: 5s
            retries: 5

    backend:
        build:
            context: ./BackendAppProducto
        ports:
            - "5000:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ConnectionStrings__PostgreSQLConnection=Host=db;Port=5432;Database=productosdb;Username=admin;Password=Admin
        networks:
            - mynetwork
        depends_on:
            db:
                condition: service_healthy

    frontend:
        build:
            context: ./FrontendAppProducto
        ports:
            - "4200:80"
        networks:
            - mynetwork
        depends_on:
            - backend

volumes:
    postgres_data:


networks:
    mynetwork:
        driver: bridge
